# (c) 2026 DRX Dev Team

import os

import bpy

__all__ = ["bone", "s2clip"]

def toBlender(fname):
	from . import s2clip
	with open(fname, "r") as file:
		lines = file.readlines()
		defaults = ['idle', 'clips/idle.clip', '0', '-1', '30', '0', '0']
		filepath = fname[0:fname.rfind(os.sep)+1]
		print(filepath)
		# create all the actions
		for line in lines:
			if line.startswith('makeanim'):
				cmd = line.split()[1:]		
				cmd = cmd + defaults[len(cmd):]

				try:
					c = s2clip.S2Clip()
					c.loadFile(filepath+cmd[1])
					clip = bpy.data.actions.new(cmd[0])
					clip.frame_start = int(cmd[2])
					clip.frame_end = int(cmd[3])
					clip.use_cyclic = (int(cmd[5]) == 1)
					
					
				except Exception as e:
					print(e)


def fromBlender(fname):
	with open(fname, "w") as file:
		print("//Generated by S2Model Blender plugin\n\n", file=file)
		print("//syntax", file=file)
		print("//makeanim AnimName ClipFile StartFrame NumFrames FPS Loop(0 or 1) Loopbackframe", file=file)
		print(file=file)
		
		for action in bpy.data.actions:
			print("makeanim %s clip/%s.clip %d %d %d %d" % (action.name, action.name, action.frame_range[0], action.frame_range[1]-action.frame_range[0], bpy.data.scenes[0].render.fps, action.use_cyclic), file=file)

		print('bipedsetup Bip01 "Bip01 R Thigh,Bip01 L Thigh"', file=file)
	